name: Merge to Backup

on:
  push:
    branches:
      - development

jobs:
  push-to-backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Fetch all branches
      run: git fetch --all
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

    - name: Create and switch to backup branch
      run: |
        git checkout -B backup origin/backup || git checkout -b backup
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

    - name: Merge development into backup
      run: git merge --allow-unrelated-histories -X theirs origin/development
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

    - name: Push changes to backup
      run: git push origin backup
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
