name: Push to Backup

on:
  push:
    branches:
      - development

jobs:
  push-to-backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push to Backup branch
      run: |
        git config --global user.email "midnight342@gmail.com"
        git config --global user.name "midnightgb"
        git checkout -b backup
        git push origin backup
      env:
        GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
